---
- debug: 
    var: letsencrypt_cert_command

- name: Obtain or renew certificate for domains
  shell: "{{ letsencrypt_cert_command }}"
  args:
    executable: /bin/bash
  register: letsencrypt_certbot
  until: letsencrypt_certbot is not failed
  retries: 3
  delay: 5
  throttle: 5
  changed_when: ('Congratulations!' in letsencrypt_certbot.stdout)

- debug: 
    var: letsencrypt_certbot
