---
- debug: var=letsencrypt_cert_command

- name: Obtain or renew certificate for domains
  shell: "{{ letsencrypt_cert_command }}"
  args:
    executable: /bin/bash
    #creates: "/etc/letsencrypt/live/{{ letsencrypt_cert_name }}"
  register: letsencrypt_certbot
  changed_when: ('Congratulations!' in letsencrypt_certbot.stdout)
  notify: Restart apache2
