---
- debug: var=letsencrypt_cert_command

- name: Obtain or renew certificate for domains
  shell: executable=/bin/bash {{ letsencrypt_cert_command }}
  register: letsencrypt_certbot
  changed_when: ('Congratulations!' in letsencrypt_certbot.stdout)
  #args:
  #  creates: "/etc/letsencrypt/live/{{ letsencrypt_cert_domains[0] }}"
  notify: Restart apache2