---
- debug: var=letsencrypt_cert_command

- name: Obtain or renew certificate for domains
  shell: "{{ letsencrypt_cert_command }}"
  args:
    executable: /bin/bash
  register: letsencrypt_certbot
  changed_when: ('Congratulations!' in letsencrypt_certbot.stdout)

- debug: var=letsencrypt_certbot
