---
- name: Install required os packages
  package: state=present pkg="{{ letsencrypt_required_packages }}" install_recommends=no update_cache=yes cache_valid_time=3600

- name: Install required pip packages
  pip:
    name: pip
    state: latest
    virtualenv: /opt/certbot/
    virtualenv_command: 'python3 -m venv'

- name: Install certbot packages
  pip:
    name: certbot
    state: latest
    virtualenv: /opt/certbot/

- name: Create symlink for certbot command
  file: 
    src: /opt/certbot/bin/certbot
    dest: /usr/bin/certbot
    state: link 
    force: yes
