---
- name: Install Let's Encrypt renewal cron job
  become: yes
  cron: name="Renew Let's Encrypt certificates"
        job="chronic {{ letsencrypt_renewal_command }} {{ letsencrypt_renewal_command_args }}"
        cron_file=letsencrypt-renewal
        user=root
        day="{{ letsencrypt_renewal_frequency.day }}"
        hour="{{ letsencrypt_renewal_frequency.hour }}"
        minute="{{ letsencrypt_renewal_frequency.minute }}"
