---
# handlers file for ansible-role-letsencrypt
- name: Reload apache2
  service: name="{{ apache2_svc }}" state=reloaded
  become: yes

- name: Restart apache2
  service: name="{{ apache2_svc }}" state=restarted
  become: yes
